# Site settings
title: "nuft"
email: the.chaotic.coder@gmail.com
description: sharing my projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nuft.github.io"
github_username:  nuft

# Build settings
markdown: kramdown
