# Site settings
title: "My Blog"
email: mspieler101@gmail.com
description: /* the world runs on code */
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nuft.github.io"
github_username:  nuft

# Build settings
markdown: kramdown
